### PR TITLE
update example to use .packet_size

### PR DESCRIPTION
**Pull request by dhalbert**
Remove workaround for bad `.packet_size` that is fixed in CircuitPython 5.0.0-beta.5

@dherrada @dglaude Note this fix.

### CODE REVIEW

**Comment by evaherrada** [comment]
@dhalbert Do you think this might work as a a fix to CircuitPython_Apple_Media? I'll test this pr in a few hours if no one else has by then

**Comment by dhalbert** [comment]
> @dhalbert Do you think this might work as a a fix to CircuitPython_Apple_Media? I'll test this pr in a few hours if no one else has by then

[answering in BaseCamp thread]

**Comment by dhalbert** [comment]
@dherrada Did you test this and it worked? If so can you approve, or if you can't, I'll just merge.

**Comment by evaherrada** [comment]
@dhalbert I haven’t tested this yet although I should do that before pyloton gets merged. Will test in 2 mins

**Comment by evaherrada** [comment]
Works great!

**Review by evaherrada — APPROVED** [review]

**Pull request merged**
